[project]
authors = ["Scott Henderson <scottyhq@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "stv-aux-data"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
wesm2geoparquet = "python wesm_gpkg_to_geoparquet.py"

[dependencies]
# Unconstrained latest version of geopandas
geopandas = "*"
pyarrow = "*"
cloudpathlib-s3 = ">=0.20.0,<0.21"
ipython = ">=8.29.0,<9"
ipykernel = ">=6.29.5,<7"



[feature.test.dependencies]
geopandas = "<1"
shapely = "<2"
rtree = "*"
pyogrio = "*"

[environments]
test = ["test"]
