name: Update WESM Metadata

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  pixi-pdal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1

      - name: Run PDAL workflow
        env:
          MAXAR_API_KEY: ${{ secrets.MAXAR_API_KEY}}
        run: |
          pixi run pdal
