name: Update WESM Metadata

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  pixi-wesm2geoparquet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1

      - name: Update Auxiliary WESM Data
        env:
          CLOUDPATHLIB_FORCE_OVERWRITE_FROM_CLOUD: 1
        run: |
          pixi run wesm2geoparquet
          ls -tlrh

      # Commit files back to repository
      - name: Commit updated CSV
        uses: EndBug/add-and-commit@v9
        with:
          push: True
          default_author: github_actions
